---
server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gmadalon/spring-cloud-netflix
          searchPaths: config-files
        native:
          searchLocations: classpath:offline-repository/